// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnpV8W8qC0O2Bx_7_18xIBcSYt-RLUQSE',
    appId: '1:865767688609:web:bf83776dca644190b7e3e0',
    messagingSenderId: '865767688609',
    projectId: 'qr-mobile-scanner',
    authDomain: 'qr-mobile-scanner.firebaseapp.com',
    storageBucket: 'qr-mobile-scanner.firebasestorage.app',
    measurementId: 'G-YWDQ498ZRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjOIrrWyANSbF3kZEoXY3VOixGVtjgkWc',
    appId: '1:865767688609:android:47dbc0033e3645f8b7e3e0',
    messagingSenderId: '865767688609',
    projectId: 'qr-mobile-scanner',
    storageBucket: 'qr-mobile-scanner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEhr0b8-_FRoa6pRWI8Xj1oZqzOi0_TbY',
    appId: '1:865767688609:ios:9f1b5d17daec1203b7e3e0',
    messagingSenderId: '865767688609',
    projectId: 'qr-mobile-scanner',
    storageBucket: 'qr-mobile-scanner.firebasestorage.app',
    iosBundleId: 'com.cgcvdev.gymcheckin.poc',
  );
}
